import { GetStaticProps } from 'next'

import Head from 'next/head'
import Image from 'next/image';
import Header from '../components/Dashboard/HeaderDashboard'
import Banner from '../components/Dashboard/Banner'
import Card from '../components/Dashboard/Card'
import Loader from '../components/Dashboard/Loader'
import Footer from '../components/Dashboard/Footer'

import { api } from '../services/api'

import styles from '../styles/components/Dashboard/Dashboard.module.css'

export default function Dashboard({ posts }) {
    return (
        <div>
            <Head>
                <title>Eduick | Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.svg" />

                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&family=Poppins:wght@400;700&display=swap" rel="stylesheet" />

                <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous" />
            </Head>

            <div className="dashboard">
                <Header />
                <div className={styles.container}>
                    <Banner />

                    <div className={styles.wrapper}>
                        <div className={styles.content}>
                            {posts.map((post) => {
                                return (
                                    <Card
                                        key={post.id}
                                        image={post.thumbnail}
                                        rating={post.rating}
                                        lessons={post.lessons}
                                        title={post.title}
                                    />
                                )
                            })}


                        </div>
                        <Loader />
                    </div>
                </div>
                <Footer />

            </div>
        </div>
    )
}

export const getStaticProps = async () => {
    const { data } = await api.get('posts', {
        params: {
            _order: 'desc'
        }
    })

    const posts = data.map(post => {
        return {
            id: post.id,
            title: post.title,
            lessons: post.lessons,
            rating: post.rating,
            thumbnail: post.thumbnail,

        };
    })

    return {
        props: {
            posts
        },
        revalidate: 60 * 60 * 12,
    }
}
