import { GetStaticProps } from 'next'

import Head from 'next/head'
import Header from '../components/Dashboard/HeaderDashboard'
import Banner from '../components/Dashboard/Banner'
import Card from '../components/Dashboard/Card'
import Loader from '../components/Dashboard/Loader'
import Footer from '../components/Dashboard/Footer'

import { api } from '../services/api'

import styles from '../styles/components/Dashboard/Dashboard.module.css'
import { Overlay } from '../components/Nav/Overlay'
import { useAppContext } from '../context/state'

export default function Dashboard({ posts }) {
    const { isOpen } = useAppContext();

    return (
        <>
            <Head>
                <title>Eduick | Dashboard</title>
                <meta name="description" content="Generated by create next app" />

                <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous" />
            </Head>

            <div className="dashboard">
                <Header />
                <Overlay isOpen={isOpen} color={'#FFFFFF80'} />
                <div className={styles.container}>
                    <Banner />

                    <div className={styles.wrapper}>
                        <div className={styles.content}>

                            {/* Create the data cards, passing the data fecthed from the API */}
                            {posts.map((post) => {
                                return (
                                    <Card
                                        key={post.id}
                                        image={post.thumbnail}
                                        rating={post.rating}
                                        lessons={post.lessons}
                                        title={post.title}
                                    />
                                )
                            })}


                        </div>
                        <Loader />
                    </div>
                </div>
                <Footer />

            </div>
        </>
    )
}

// Make a single call to the api to fetch the data
export const getStaticProps = async () => {
    const { data } = await api.get('posts', {
        params: {
            _order: 'desc'
        }
    })

    // create a map of the data received
    const posts = data.map(post => {
        return {
            id: post.id,
            title: post.title,
            lessons: post.lessons,
            rating: post.rating,
            thumbnail: post.thumbnail,

        };
    })

    // return the data fetched and revalidade on each 12 hours passed;
    return {
        props: {
            posts
        },
        revalidate: 60 * 60 * 12,
    }
}
