import Head from 'next/head'
import Header from '../components/Dashboard/HeaderDashboard'
import Banner from '../components/Dashboard/Banner'
import Card from '../components/Dashboard/Card'
import Loader from '../components/Dashboard/Loader'
import Footer from '../components/Dashboard/Footer'

import styles from '../styles/components/Dashboard/Dashboard.module.css'

export default function Dashboard() {
    return (
        <div>
            <Head>
                <title>Eduick | Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.svg" />

                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&family=Poppins:wght@400;700&display=swap" rel="stylesheet" />

                <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous" />
            </Head>

            <div className="dashboard">
                <Header />
                <div className={styles.container}>
                    <Banner />

                    <div className={styles.content}>
                        <div className={styles.row}>
                            <Card />
                            <Card />
                            <Card />
                        </div>
                        <div className={styles.row}>
                            <Card />
                            <Card />
                            <Card />
                        </div>

                        <Loader />
                    </div>

                </div>
                <Footer />
            </div>

        </div>
    )
}
