import Head from 'next/head'
import { Header } from '../components/Landing/Header'
import { Landing } from '../components/Landing/Landing'
import styles from '../styles/components/Landing/home.module.css';

export default function Home() {
	return (
		<div className={styles.home}>
			<Head>
				<title>Eduick</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.svg" />

				<link rel="preconnect" href="https://fonts.gstatic.com" />
				<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&family=Poppins:wght@400;700&display=swap" rel="stylesheet" />

				<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous" />
			</Head>

			<Header />

			<Landing />

		</div>
	)
}
